services:
  postgres:
    image: postgres:16-alpine
    container_name: blaff-db
    environment:
      POSTGRES_USER: blauser
      POSTGRES_PASSWORD: blapass
      POSTGRES_DB: blaff
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blauser -d blaff"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
